"""Contains constants for initializing game window."""

VERSION_NUM = (0, 3, 2)

WINDOW_CAPTION = "JJJ Asteroids"
WINDOW_ICON_PATH = "window_icon"

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
PIXEL_SCALE = 2

MAX_FPS = 60
TICKRATE = 20


WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

PIXEL_WINDOW_WIDTH = WINDOW_SIZE[0]//PIXEL_SCALE
PIXEL_WINDOW_HEIGHT = WINDOW_SIZE[1]//PIXEL_SCALE
PIXEL_WINDOW_SIZE = (PIXEL_WINDOW_WIDTH, PIXEL_WINDOW_HEIGHT)