"""Contains constants for initializing game window."""

VERSION_NUM = (0, 9, 1)

WINDOW_CAPTION = "SpaceRocks"
WINDOW_ICON_PATH = "window_icon"

PIXEL_WINDOW_WIDTH = 320
PIXEL_WINDOW_HEIGHT = 240

PIXEL_WINDOW_SIZE = (PIXEL_WINDOW_WIDTH, PIXEL_WINDOW_HEIGHT)
PIXEL_SCALE = 2

WINDOW_WIDTH = PIXEL_WINDOW_WIDTH*PIXEL_SCALE
WINDOW_HEIGHT = PIXEL_WINDOW_HEIGHT*PIXEL_SCALE

WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

FRAMERATE = 60
TICKRATE = 20