"""Contains constants for initializing game window."""

VERSION_NUM = (0, 8, 3, "generated_levels")

WINDOW_CAPTION = "SpaceRocks"
WINDOW_ICON_PATH = "window_icon"

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480

WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

PIXEL_SCALE = 2
PIXEL_WINDOW_WIDTH = WINDOW_WIDTH//PIXEL_SCALE
PIXEL_WINDOW_HEIGHT = WINDOW_HEIGHT//PIXEL_SCALE

PIXEL_WINDOW_SIZE = (PIXEL_WINDOW_WIDTH, PIXEL_WINDOW_HEIGHT)

FRAMERATE = 60
TICKRATE = 20

LOAD_ASSETS_FROM_APP_DATA = False